### ISSUE TITLE
Special charecters [<>] are not handled correctly.

### ISSUE THREAD

**Issue by firefish5000** [alexander-yakushev/awesompd#30]
various errors are being thrown when playing songs with '<' and '>' in the title since they are not escaped.

Please consider adding a mapping to translate '<' to '\&lt;' and '>' to '\&gt;', or possibly consider using awful.util.escape() instead of utf8.replace().
On that note, awful.util.escape() seems to also escape double quotes, though I can play songs with quotes in the title without a problem, so that may be unnecessary.

example title
  Short Drama [\<Oshiete! Wataru Tenchou\> Makai Gekitou Hen~ Maou Toujou!]
this throws various error messages, depending on what would have been displayed in the wibox.
  /usr/share/awesome/lib/wibox/widget/textbox.lua:61 (various error messages)

**Comment by alexander-yakushev** [comment]
Oops, I see this was left unattended for quite some time, sorry. Do I understand correctly that this was fixed with #33?

**Comment by firefish5000** [comment]
Yes.
FWIW, I checked the notify, textbox, and menu specifically with lt(<), gt(>), and amp(&). I didn't notice any problems with any of them, and I haven't had any (related) error messages since the change. Since it's part of awesomewm, it should escape all special chars(from memory, pango markup chars).

**Comment by alexander-yakushev** [comment]
Good. It's possible that I hadn't been aware of this function when I was writing that code.
